spring.application.name=Relationship
spring.datasource.url=jdbc:postgresql://localhost:5432/relationship
spring.datasource.username=postgres
spring.datasource.password=1111
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081

#// upload file and save path video



spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB
app.upload.dir=${user.dir}/E-commerch/uploads
