spring.application.name=Relationship
spring.datasource.url=jdbc:postgresql://localhost:5432/relationship
spring.datasource.username=postgres
spring.datasource.password=1111
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081

# Run schema.sql on startup (needed to fix old constraints that ddl-auto=update won't alter)
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

#// upload file and save path video



spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB
app.upload.dir=${user.dir}/E-commerch/uploads
